ExternalProject_Add(doxygen
	URL https://www.doxygen.nl/files/doxygen-1.12.0.src.tar.gz
	URL_MD5 3ab97fd76c6fe090946c836c5051182b

	CMAKE_ARGS
		-DPKG_CONFIG_EXECUTABLE=${PKG_CONFIG_EXECUTABLE}
		-DCMAKE_PREFIX_PATH=${CMAKE_BINARY_DIR}/dep-install/
		-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/dep-install/
		-DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=On
	EXCLUDE_FROM_ALL
)
