ExternalProject_Add(doxygen
	URL http://doxygen.nl/files/doxygen-1.8.15.src.tar.gz
	URL_MD5 2c98c73eba392d334f5bbaf15e09bae3

	CMAKE_ARGS
		-DPKG_CONFIG_EXECUTABLE=${PKG_CONFIG_EXECUTABLE}
		-DCMAKE_PREFIX_PATH=${CMAKE_BINARY_DIR}/dep-install/
		-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/dep-install/
		-DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=On
	EXCLUDE_FROM_ALL
)
